/* 调酒数据：六大基酒，共 17 款经典调酒（龙舌兰 2 款，其余各 3 款） */
const SPIRITS = [
  {
    id: "whisky",
    name: "威士忌",
    en: "WHISKY",
    desc: "琥珀色的谷物烈酒，经橡木桶陈年，烟熏、蜂蜜与木香交织。",
    drinks: [
      {
        zh: "古典",
        en: "Old Fashioned",
        img: "assets/drinks/old-fashioned.webp",
        ingredients: [
          ["波本威士忌", "60 ml"],
          ["方糖", "1 块"],
          ["安格仕苦精", "2-3 dash"],
          ["苏打水", "少许"],
        ],
        method: "搅拌法 Stir",
        steps: [
          "方糖与苦精入古典杯，加少许苏打水压碎化开；",
          "放一大块方冰，倒入波本威士忌；",
          "吧勺缓慢搅拌约 30 秒，至充分冷却；",
          "橙皮喷香后投入，即可。",
        ],
        glass: "古典杯（洛克杯）",
        garnish: "橙皮喷香，大块方冰",
      },
      {
        zh: "威士忌酸",
        en: "Whiskey Sour",
        img: "assets/drinks/whiskey-sour.webp",
        ingredients: [
          ["波本威士忌", "60 ml"],
          ["鲜柠檬汁", "22 ml"],
          ["糖浆", "15 ml"],
          ["蛋清（可选）", "1 个"],
        ],
        method: "摇和法 Shake",
        steps: [
          "波本、柠檬汁、糖浆与蛋清依次入波士顿摇壶；",
          "先无冰干摇约 10 秒，打发蛋清；",
          "加冰再摇约 15 秒，至壶身结霜；",
          "双重过滤入冰镇酸酒杯，柠檬片与酒渍樱桃装饰。",
        ],
        shaker: "波士顿摇壶",
        shakeTime: "约 15 秒（另干摇 10 秒）",
        glass: "酸酒杯 / 古典杯",
        garnish: "柠檬片与酒渍樱桃",
      },
      {
        zh: "曼哈顿",
        en: "Manhattan",
        img: "assets/drinks/manhattan.webp",
        ingredients: [
          ["黑麦威士忌", "60 ml"],
          ["甜味美思", "20 ml"],
          ["安格仕苦精", "2 dash"],
        ],
        method: "搅拌法 Stir",
        steps: [
          "黑麦威士忌、甜味美思与苦精入调酒杯；",
          "加冰，吧勺搅拌约 30 秒至冰冷顺滑；",
          "滤入冰镇碟形杯；",
          "酒渍樱桃一枚装饰。",
        ],
        glass: "碟形香槟杯 Coupe",
        garnish: "酒渍樱桃一枚",
      },
    ],
  },
  {
    id: "rum",
    name: "朗姆",
    en: "RUM",
    desc: "甘蔗孕育的烈酒，清甜奔放，是加勒比海与热带岛屿的灵魂。",
    drinks: [
      {
        zh: "莫吉托",
        en: "Mojito",
        img: "assets/drinks/mojito.webp",
        ingredients: [
          ["白朗姆", "50 ml"],
          ["鲜青柠汁", "25 ml"],
          ["糖浆", "20 ml"],
          ["薄荷叶", "8-10 片"],
          ["苏打水", "补满"],
        ],
        method: "轻捣直调 Muddle & Build",
        steps: [
          "薄荷叶与糖浆入高球杯，轻压出香（勿捣烂）；",
          "加青柠汁与白朗姆，填入碎冰；",
          "搅匀后苏打水补满；",
          "薄荷束与青柠角装饰。",
        ],
        glass: "高球杯 Highball",
        garnish: "薄荷束与青柠角",
      },
      {
        zh: "代基里",
        en: "Daiquiri",
        img: "assets/drinks/daiquiri.webp",
        ingredients: [
          ["白朗姆", "60 ml"],
          ["鲜青柠汁", "22 ml"],
          ["糖浆", "15 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "白朗姆、青柠汁、糖浆依次入三段式摇壶；",
          "加冰用力摇约 10-15 秒，至壶身结霜；",
          "双重过滤入冰镇碟形杯；",
          "青柠薄片装饰。",
        ],
        shaker: "三段式摇壶",
        shakeTime: "约 10-15 秒",
        glass: "碟形香槟杯 Coupe",
        garnish: "青柠薄片",
      },
      {
        zh: "自由古巴",
        en: "Cuba Libre",
        img: "assets/drinks/cuba-libre.webp",
        ingredients: [
          ["白朗姆", "50 ml"],
          ["可乐", "120 ml"],
          ["鲜青柠汁", "10 ml"],
        ],
        method: "直调法 Build",
        steps: [
          "高球杯加满冰，倒入白朗姆与青柠汁；",
          "可乐沿吧勺缓缓补满；",
          "轻提一下吧勺即可，青柠角装饰。",
        ],
        glass: "高球杯 Highball",
        garnish: "青柠角",
      },
    ],
  },
  {
    id: "gin",
    name: "金酒",
    en: "GIN",
    desc: "杜松子领军的草本烈酒，干冽清冽，是无数经典调酒的起点。",
    drinks: [
      {
        zh: "金汤力",
        en: "Gin & Tonic",
        img: "assets/drinks/gin-tonic.webp",
        ingredients: [
          ["干金酒", "50 ml"],
          ["汤力水", "120-150 ml"],
        ],
        method: "直调法 Build",
        steps: [
          "高球杯加满冰，倒入干金酒；",
          "汤力水沿吧勺缓缓注入；",
          "轻搅一圈保留气泡，青柠角或杜松子装饰。",
        ],
        glass: "高球杯 Highball",
        garnish: "青柠角或杜松子",
      },
      {
        zh: "马天尼",
        en: "Martini",
        img: "assets/drinks/martini.webp",
        ingredients: [
          ["干金酒", "60 ml"],
          ["干味美思", "10 ml"],
        ],
        method: "搅拌法 Stir",
        steps: [
          "干金酒与干味美思入调酒杯；",
          "加冰搅拌至冰冷，滤入冰镇马天尼杯；",
          "绿橄榄或柠檬皮卷装饰。",
        ],
        glass: "马天尼杯 Martini",
        garnish: "绿橄榄或柠檬皮卷",
      },
      {
        zh: "尼格罗尼",
        en: "Negroni",
        img: "assets/drinks/negroni.webp",
        ingredients: [
          ["干金酒", "30 ml"],
          ["金巴利", "30 ml"],
          ["甜味美思", "30 ml"],
        ],
        method: "搅拌法 Stir",
        steps: [
          "金酒、金巴利、甜味美思等比入调酒杯；",
          "加冰搅拌约 30 秒，至充分冷却；",
          "滤入装有大冰块的古典杯；",
          "橙皮喷香。",
        ],
        glass: "古典杯（洛克杯）",
        garnish: "橙皮喷香",
      },
    ],
  },
  {
    id: "tequila",
    name: "龙舌兰",
    en: "TEQUILA",
    desc: "蓝色龙舌兰草之心酿成，辛烈明亮，带着墨西哥的阳光与野性。",
    drinks: [
      {
        zh: "玛格丽特",
        en: "Margarita",
        img: "assets/drinks/margarita.webp",
        ingredients: [
          ["龙舌兰", "50 ml"],
          ["君度橙酒", "20 ml"],
          ["鲜青柠汁", "15 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "杯口沾青柠汁后滚盐，做出盐边；",
          "龙舌兰、君度、青柠汁入三段式摇壶，加冰摇约 10-15 秒；",
          "滤入冰镇杯中；",
          "青柠角装饰。",
        ],
        shaker: "三段式摇壶",
        shakeTime: "约 10-15 秒",
        glass: "玛格丽特杯 / 碟形杯",
        garnish: "杯口盐边，青柠角",
      },
      {
        zh: "龙舌兰日出",
        en: "Tequila Sunrise",
        img: "assets/drinks/tequila-sunrise.webp",
        ingredients: [
          ["龙舌兰", "45 ml"],
          ["鲜橙汁", "90 ml"],
          ["红石榴糖浆", "15 ml"],
        ],
        method: "直调法 Build",
        steps: [
          "高球杯加冰，倒入龙舌兰与橙汁搅匀；",
          "红石榴糖浆沿吧勺缓缓沉入杯底；",
          "形成日出般的渐变，橙片与樱桃装饰。",
        ],
        glass: "高球杯 Highball",
        garnish: "橙片与樱桃",
      },
    ],
  },
  {
    id: "vodka",
    name: "伏特加",
    en: "VODKA",
    desc: "纯净中性、几乎无色无味的烈酒，是调酒师手中最干净的画布。",
    drinks: [
      {
        zh: "莫斯科骡子",
        en: "Moscow Mule",
        img: "assets/drinks/moscow-mule.webp",
        ingredients: [
          ["伏特加", "50 ml"],
          ["鲜青柠汁", "15 ml"],
          ["姜汁啤酒", "100-120 ml"],
        ],
        method: "直调法 Build",
        steps: [
          "铜马克杯装满冰；",
          "倒入伏特加与青柠汁，姜汁啤酒补满；",
          "轻搅，青柠角与薄荷装饰。",
        ],
        glass: "铜马克杯 Copper Mug",
        garnish: "青柠角与薄荷",
      },
      {
        zh: "大都会",
        en: "Cosmopolitan",
        img: "assets/drinks/cosmopolitan.webp",
        ingredients: [
          ["伏特加", "40 ml"],
          ["君度橙酒", "15 ml"],
          ["蔓越莓汁", "30 ml"],
          ["鲜青柠汁", "15 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "伏特加、君度、蔓越莓汁、青柠汁入三段式摇壶；",
          "加冰摇约 10-15 秒，至冰冷；",
          "双重过滤入冰镇马天尼杯；",
          "橙皮喷香。",
        ],
        shaker: "三段式摇壶",
        shakeTime: "约 10-15 秒",
        glass: "马天尼杯 Martini",
        garnish: "橙皮喷香",
      },
      {
        zh: "浓缩咖啡马天尼",
        en: "Espresso Martini",
        img: "assets/drinks/espresso-martini.webp",
        ingredients: [
          ["伏特加", "50 ml"],
          ["咖啡利口酒", "20 ml"],
          ["浓缩咖啡", "30 ml"],
          ["糖浆", "5 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "伏特加、咖啡利口酒、浓缩咖啡、糖浆入波士顿摇壶；",
          "加冰用力摇约 15 秒，打出绵密泡沫；",
          "双重过滤入冰镇马天尼杯；",
          "三粒咖啡豆浮于泡沫之上。",
        ],
        shaker: "波士顿摇壶",
        shakeTime: "约 15 秒",
        glass: "马天尼杯 Martini",
        garnish: "三粒咖啡豆",
      },
    ],
  },
  {
    id: "brandy",
    name: "白兰地",
    en: "BRANDY",
    desc: "葡萄酒蒸馏后的琥珀精华，温润优雅，岁月在桶中沉淀出的香气。",
    drinks: [
      {
        zh: "边车",
        en: "Sidecar",
        img: "assets/drinks/sidecar.webp",
        ingredients: [
          ["白兰地", "50 ml"],
          ["君度橙酒", "20 ml"],
          ["鲜柠檬汁", "20 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "杯口沾柠檬汁滚糖，做出糖边（可选）；",
          "白兰地、君度、柠檬汁入三段式摇壶，加冰摇约 10-15 秒；",
          "滤入冰镇碟形杯；",
          "橙皮卷装饰。",
        ],
        shaker: "三段式摇壶",
        shakeTime: "约 10-15 秒",
        glass: "碟形香槟杯 Coupe",
        garnish: "橙皮卷",
      },
      {
        zh: "白兰地亚历山大",
        en: "Brandy Alexander",
        img: "assets/drinks/brandy-alexander.webp",
        ingredients: [
          ["白兰地", "30 ml"],
          ["黑可可利口酒", "30 ml"],
          ["淡奶油", "30 ml"],
        ],
        method: "摇和法 Shake",
        steps: [
          "白兰地、黑可可利口酒、淡奶油入波士顿摇壶；",
          "加冰用力摇约 15 秒，至口感绵密；",
          "双重过滤入冰镇碟形杯；",
          "现磨肉豆蔻粉撒于表面。",
        ],
        shaker: "波士顿摇壶",
        shakeTime: "约 15 秒",
        glass: "碟形香槟杯 Coupe",
        garnish: "现磨肉豆蔻粉",
      },
      {
        zh: "萨泽拉克",
        en: "Sazerac",
        img: "assets/drinks/sazerac.webp",
        ingredients: [
          ["白兰地（干邑）", "60 ml"],
          ["苦艾酒", "10 ml（涮杯）"],
          ["方糖", "1 块"],
          ["佩乔苦精", "3 dash"],
        ],
        method: "搅拌法 Stir",
        steps: [
          "苦艾酒倒入冰镇古典杯，涮杯后弃去；",
          "白兰地、方糖、佩乔苦精入调酒杯，加冰搅拌至冰冷；",
          "滤入涮好的杯中；",
          "柠檬皮挤油后弃去。",
        ],
        glass: "古典杯（洛克杯）",
        garnish: "柠檬皮挤油后弃去",
      },
    ],
  },
];
